apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: gin-qa-solutions
        image: 172.31.27.186:5000/gin-qa-solutions:1.0.2
        volumeMounts:
        - name: content
          mountPath: /usr/share/gin-qa-solutions/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: kargo-demo-content
      initContainers:
      - name: download
        image: ubuntu
        command: ["/usr/bin/env"]
        args: ['git clone https://github.com/pc085n/gin-test.git']
        volumeMounts:
        - name: source
          mountPath: /home/ubuntu/gin-test
