apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo
  template:
    metadata:
      labels:
        app: kargo
    spec:
      containers:
      - name: Clone gin-test repository
        args: 
            - git
            - clone
            - https://github.com/pc085n/gin-test.git
            - gin
        volumeMounts:
        - name: gin-test
          mountPath: gin
      - name: Robot framework
        image: gin-qa-solutions
        args:
            - docker
            - run
            - -v
            - /home/ubuntu/gin/:/gin/
            - gin-qa-solutions:latest
            - /gin/results/
            - /gin/tests/Main.robot
        volumeMounts:
        - name: content
          mountPath: /usr/share/robotframework/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: kargo-content
