apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: gin-qa-solutions
        image: docker.io/ccipearl/gin-qa-solutions@sha256:51bd95e79c57cc2d2151c833d42ca8997cebb92ad08e6e6afe66cd283ecaa32e
        volumeMounts:
        - name: content
          mountPath: /usr/share/robotframework/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: kargo-demo-content
