apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo
  template:
    metadata:
      labels:
        app: kargo
    spec:
      containers:
      - name: Clone gin-test repository
        args: 
            - git
            - clone
            - https://github.com/pc085n/gin-test.git
            - gin
        volumeMounts:
        - name: gin-test
          mountPath: gin
      volumes:
      - name: content
        configMap:
          name: kargo-content
