apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- target:
    kind: Service
    name: kargo-demo
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30083
images:
- name: 172.31.27.186:5000/gin-qa-solutions
  newName: 172.31.27.186:5000/gin-qa-solutions
  newTag: 1.0.2
